spring:
  # Application configuration
  application:
    name: incident-validator
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: IncidentValidatorHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000
  
  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  
  # Jackson configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    time-zone: ${TIMEZONE}
  
  # Servlet configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  # Profile configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

# Logging configuration
logging:
  level:
    root: ${ROOT_LOG_LEVEL}
    com.gfour.api: ${APP_LOG_LEVEL}
    org.hibernate.SQL: ${SQL_LOG_LEVEL}
    org.hibernate.type.descriptor.sql.BasicBinder: ${SQL_PARAM_LOG_LEVEL}
  file:
    name: ${LOG_FILE}

# Server configuration
server:
  port: ${PORT}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
  servlet:
    context-path: /

# Springdoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
  show-actuator: true
  paths-to-match: /api/**

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Application-specific configuration
application:
  file-processing:
    delimiter: ";"
    date-format: "yyyy-MM-dd HH:mm:ss"
    max-line-errors: 100
    batch-size: 500
  security:
    jwt:
      secret: ${JWT_SECRET}
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS}
      allowed-methods: "*"
      allowed-headers: "*"
      exposed-headers: "Authorization,Link,X-Total-Count"
      allow-credentials: true
      max-age: 1800